In [1]:
# Numpy  ->   Numerical Python   | Linear Algebra, Statistics   |  N-Dimensional Arrays   |  Vector Operations  | Memory efficient

In [2]:
nums  = [1,2,3,4,5]

In [5]:
[i*2 for i in nums ]

[2, 4, 6, 8, 10]

In [6]:
# numpy uses Contiguous Memory 

In [7]:
import numpy  as np 

In [10]:
np.array(nums) 

array([1, 2, 3, 4, 5])

In [12]:
np.array(nums) * 2    #  less code, much faster ,  Cleaner and readable 

array([ 2,  4,  6,  8, 10])

In [18]:
# ndarray   #  homogeneous datatypes  

In [14]:
num_1d = [1,2,3,4,5,6]

In [15]:
np.array(num_1d) 

array([1, 2, 3, 4, 5, 6])

In [16]:
nums_2d = [[1,2],[3,4]]

In [17]:
np.array(nums_2d)

array([[1, 2],
       [3, 4]])

In [24]:
#  Array Attribute

In [19]:
arr = np.array([1,2,3,4,5,6])

In [20]:
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
arr.shape 

(6,)

In [22]:
arr = np.array([[1,2,3],[4,5,6]])

In [23]:
arr.shape 

(2, 3)

In [25]:
arr.ndim

2

In [26]:
arr.size 

6

In [27]:
arr.dtype 

dtype('int64')

In [28]:
#  Common array creation methods

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(3) * 5 

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [34]:
arr = np.array([1,2,3,4,5,6])

In [36]:
arr

array([1, 2, 3, 4, 5, 6])

In [37]:
arr[0]

np.int64(1)

In [38]:
arr[2:]

array([3, 4, 5, 6])

In [39]:
matrix = np.array([[1,2,3],[4,5,6]])

In [40]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
matrix[1]

array([4, 5, 6])

In [42]:
matrix[0]

array([1, 2, 3])

In [44]:
matrix[:,1:]

array([[2, 3],
       [5, 6]])

In [45]:
# Vectorized Operations 

In [46]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [47]:
arr1 + arr2 

array([5, 7, 9])

In [49]:
arr1 * arr2   #   no loops 

array([ 4, 10, 18])

In [50]:
arr1 = np.array([1,2,3])  

In [51]:
arr1 + 10 

array([11, 12, 13])

In [52]:
#  Aggregations 

In [54]:
data = np.array([10,20,30,40,50,60])

In [55]:
np.sum(data)

np.int64(210)

In [56]:
np.mean(data)

np.float64(35.0)

In [57]:
np.max(data)

np.int64(60)

In [58]:
np.min(data)

np.int64(10)

In [59]:
np.std(data)

np.float64(17.07825127659933)

In [60]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [61]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
matrix.shape

(3, 4)

In [64]:
matrix.sum(axis=0)  # Column Wise  

array([15, 18, 21, 24])

In [65]:
matrix.sum(axis=1) 

array([10, 26, 42])

In [66]:
matrix.min(axis=0)

array([1, 2, 3, 4])

In [67]:
matrix.min()

np.int64(1)

In [68]:
matrix.sum() 

np.int64(78)

In [69]:
data = np.array([10,20,30,40,50,60]) 

In [70]:
data    #  1*6= 6   |    2*3 = 6  | 3*2 = 6  

array([10, 20, 30, 40, 50, 60])

In [71]:
data.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [72]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

In [74]:
matrix.shape

(3, 4)

In [75]:
matrix.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [77]:
np.random.randint(1,10)

5

In [78]:
np.random.randint(1,10,6)

array([7, 5, 9, 3, 8, 4], dtype=int32)

In [79]:
num_orders = 10

In [83]:
#  order_id | prod_id | quantity | price
orders = np.zeros((num_orders,4))

In [84]:
orders

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
orders[:,0] = np.arange(1,num_orders+1)
orders[:,1] = np.random.randint(100,120,num_orders)
orders[:,2] = np.random.randint(1,5,num_orders)
orders[:,3] = np.random.uniform(100,1000,num_orders)


In [96]:
orders

array([[  1.        , 119.        ,   3.        , 412.12472454],
       [  2.        , 117.        ,   3.        , 606.73094022],
       [  3.        , 105.        ,   1.        , 191.23326657],
       [  4.        , 101.        ,   4.        , 875.5321301 ],
       [  5.        , 114.        ,   4.        , 211.41624337],
       [  6.        , 104.        ,   3.        , 764.04205169],
       [  7.        , 108.        ,   4.        , 480.53136783],
       [  8.        , 109.        ,   3.        , 769.6305017 ],
       [  9.        , 104.        ,   4.        , 317.59499017],
       [ 10.        , 101.        ,   2.        , 424.2940116 ]])

In [92]:
np.random.uniform(100,1000,10)

array([556.16493226, 771.55928815, 252.78056772, 917.18302693,
       335.30194407, 676.14126096, 193.39740818, 939.71640204,
       691.28224052, 327.50068489])